import { useState } from "react";
import { useLocation } from "wouter";
import { ArrowRight, Eye, EyeOff, ShieldCheck } from "lucide-react";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";

export default function Login() {
  const [, navigate] = useLocation();
  const [mode, setMode] = useState<"login" | "register">("login");
  const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [show, setShow] = useState(false);
  const utils = trpc.useUtils();
  const login = trpc.auth.login.useMutation({ onSuccess: (result) => { if (!result.ok) return toast.error("لا يوجد حساب بهذه البيانات"); utils.auth.me.invalidate(); navigate(result.user.role === "admin" ? "/admin" : "/"); } });
  const register = trpc.auth.register.useMutation({ onSuccess: (result) => { if (!result.ok) return toast.error("يوجد حساب بهذا البريد الإلكتروني بالفعل"); utils.auth.me.invalidate(); toast.success("تم إنشاء الحساب بنجاح"); navigate("/"); } });
  const submit = (e: React.FormEvent) => { e.preventDefault(); if (mode === "login") login.mutate({ email, password }); else register.mutate({ name, email, password }); };
  const pending = login.isPending || register.isPending;
  return <main dir="rtl" className="min-h-screen bg-[#fbfaf8] px-4 py-8 text-[#27231f]"><div className="mx-auto max-w-md"><button onClick={() => navigate("/")} className="mb-10 flex items-center gap-2 text-sm text-[#766b61]"><ArrowRight size={17}/> العودة للمتجر</button><div className="rounded-[28px] border border-[#27231f]/10 bg-white p-7 shadow-sm sm:p-10"><div className="mb-8 text-center"><div className="mx-auto mb-4 grid h-14 w-14 place-items-center rounded-2xl bg-[#f1e6d7] text-[#9b7646]"><ShieldCheck/></div><div className="font-serif text-2xl tracking-[.16em]">NADOLA</div><p className="mt-2 text-sm text-[#85796e]">{mode === "login" ? "تسجيل الدخول إلى حسابك" : "إنشاء حساب جديد"}</p></div><form onSubmit={submit} className="space-y-4">{mode === "register" && <label className="block text-sm">الاسم<input value={name} onChange={e=>setName(e.target.value)} required className="mt-2 w-full rounded-xl border border-[#27231f]/15 px-4 py-3 outline-none focus:border-[#bd8f56]"/></label>}<label className="block text-sm">البريد الإلكتروني<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required className="mt-2 w-full rounded-xl border border-[#27231f]/15 px-4 py-3 outline-none focus:border-[#bd8f56]"/></label><label className="block text-sm">كلمة السر<div className="relative mt-2"><input type={show?"text":"password"} value={password} onChange={e=>setPassword(e.target.value)} required minLength={4} className="w-full rounded-xl border border-[#27231f]/15 px-4 py-3 pl-12 outline-none focus:border-[#bd8f56]"/><button type="button" onClick={()=>setShow(!show)} className="absolute left-3 top-3 text-[#8d8176]">{show?<EyeOff size={19}/>:<Eye size={19}/>}</button></div></label><button disabled={pending} className="w-full rounded-full bg-[#27231f] py-3.5 text-sm text-white transition hover:bg-[#9b7646] disabled:opacity-50">{pending?"جارٍ التنفيذ...":mode === "login" ? "تسجيل الدخول" : "إنشاء حساب"}</button></form><div className="mt-6 text-center text-sm text-[#85796e]">{mode === "login" ? "ليس لديك حساب؟" : "لديك حساب بالفعل؟"}<button onClick={()=>setMode(mode === "login" ? "register" : "login")} className="mr-2 text-[#9b7646] underline">{mode === "login" ? "إنشاء حساب جديد" : "تسجيل الدخول"}</button></div><p className="mt-7 rounded-xl bg-[#fbf7f0] p-3 text-center text-xs leading-6 text-[#85796e]">حساب الإدارة: ibrahimahmed@gmail.com<br/>يتم حفظ الحسابات في قاعدة البيانات، ولا تظهر لوحة الإدارة للزوار.</p></div></div></main>;
}
